defaults: &defaults
  adapter: mysql2
  encoding: utf8
  username: $USERNAME
  password: $PASSWORD
  pool: 5
  host: mysql

### ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'rsi1111'; 
test: &test
  <<: *defaults
  database: timestack_test

development:
  <<: *defaults
  database: $DATABASE

cucumber:
  <<: *test
